## Python, data science, NLP, Machine Learning, Deep learning 

In [4]:
import numpy as np

In [5]:
import numpy
numpy.__version__

'1.18.2'

In [4]:
L=list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(L[0])

int

In [6]:
L2=list(str(c) for c in range(10))
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
L3=[True,0,"good",8.8]

In [9]:
[type(item) for item in L3]

[bool, int, str, float]

In [10]:
import numpy as np
arr=np.array(range(10))

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(arr)

numpy.ndarray

In [13]:
type(arr[0])

numpy.int32

In [14]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
type(A)

array.array

In [16]:
A.insert(2,6)
A

array('i', [0, 1, 6, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
A.append(5)

In [18]:
A #remove and pop functions are used to remove elements from array.

array('i', [0, 1, 6, 2, 3, 4, 5, 6, 7, 8, 9, 5])

In [19]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [21]:
np.array([range(i,i+3) for i in [1,2,3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [28]:
g=np.array([[1,2,3],[5,8,4]])

In [31]:
np.zeros(10,dtype='float')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.full((4,7),89)

array([[89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89]])

In [35]:
np.arange(0,10,4)

array([0, 4, 8])

In [37]:
np.linspace(0,1,7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [57]:
np.random.rand(6,8)# 6*8 matrix with values between 0 and 1.

array([[0.93884934, 0.86444183, 0.89611738, 0.58759598, 0.28054639,
        0.53361727, 0.58488947, 0.26343487],
       [0.8806494 , 0.4003461 , 0.09749056, 0.16154692, 0.7796181 ,
        0.7469077 , 0.34657263, 0.65868783],
       [0.37184483, 0.85239722, 0.84764434, 0.12031906, 0.46602199,
        0.55556642, 0.51132671, 0.65106298],
       [0.52537496, 0.17044812, 0.40093519, 0.59306936, 0.59722738,
        0.01491916, 0.2132296 , 0.82770364],
       [0.48714824, 0.92770832, 0.76157905, 0.1853482 , 0.38933512,
        0.22544506, 0.83250251, 0.97266244],
       [0.79470408, 0.67624734, 0.05924041, 0.26294912, 0.4005038 ,
        0.87951415, 0.82732179, 0.45857898]])

In [53]:
np.random.randint(1,100,(5,5)) #create a 5*5 array within 1 to 100 interval.

array([[36, 15, 73, 51, 78],
       [68,  3, 68, 99, 68],
       [40, 69, 91, 32, 63],
       [25, 84, 56, 77, 80],
       [79, 85, 93, 11, 86]])

In [60]:
np.random.randint(1,100,8)#1-d array.

array([85, 51, 42, 31, 84, 44, 21, 73])

In [62]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.empty(4) # don't exactly know what this is.

array([1., 1., 1., 1.])

# Numpy Array basics and operations

In [19]:
np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,3))
x3=np.random.randint(10,size=(3,3,3))
x4=np.random.randint(2,3,size=(3,3))
print(x4)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [7]:
print(x3.ndim,x3.size,x3.shape) # prints dimension,size,shape of the array.

3 27 (3, 3, 3)


In [8]:
print(x3.dtype)#type of array
print(x3.itemsize)#size of each element in bytes
print(x3.nbytes)#total size in bytes

int32
4
108


In [9]:
x1[0]

5

In [10]:
x2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [11]:
x2[2,-1]

1

In [12]:
x2[2,1]

8

In [13]:
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
x1[1]=7.8 #This value will be truncated. 

In [99]:
x1 # we can see the value 7.8 is rounded off to 7.

array([5, 7, 3, 3, 7, 9])

# Array slicing and subarrays

In [20]:
x=np.arange(10)

In [21]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[::3] #x[start:stop:step]

array([0, 3, 6, 9])

In [24]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
x[::-2]

array([9, 7, 5, 3, 1])

In [26]:
x[5::-3]

array([5, 2])

In [27]:
x2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [28]:
np.random.seed(0)
y=np.random.randint(1,100,(4,4))
print(y)
print(y[1,1])
print(y[:,:]) #prints entire array.
print("\n")
print(y[1:,:])#prints entire array except first row(from second row)
print("\n")
print(y[1:,2:])#from second row and third column
print("\n")
print(y[0])# prints first row
print("\n")
print(y[:,0]) #prints first column
print("\n")
print(y)
print("\n")
print(y[:3,:2])
print("\n")
print(y)
print("\n")
print(y[::2,1::2])
print("\n")
print(y)
print("\n")
print(y[::-1,:])
print("\n")
print(y[::-1,::-1])
print("\n")
print(y[:,::-1])

[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]]
10
[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]]


[[68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]]


[[84 22]
 [71 89]
 [59 66]]


[45 48 65 68]


[45 68 37 89]


[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]]


[[45 48]
 [68 10]
 [37 88]]


[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]]


[[48 68]
 [88 89]]


[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]]


[[89 13 59 66]
 [37 88 71 89]
 [68 10 84 22]
 [45 48 65 68]]


[[66 59 13 89]
 [89 71 88 37]
 [22 84 10 68]
 [68 65 48 45]]


[[68 65 48 45]
 [22 84 10 68]
 [89 71 88 37]
 [66 59 13 89]]


# Demonstrating difference between numpy arrays and lists

In [29]:
print(y)  

[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]]


In [30]:
y_sub=y[:2,:2]

In [31]:
print(y_sub)

[[45 48]
 [68 10]]


In [32]:
y_sub[0,1]=88 #change a value

In [33]:
y_sub

array([[45, 88],
       [68, 10]])

In [34]:
y #changed value reflects in original array

array([[45, 88, 65, 68],
       [68, 10, 84, 22],
       [37, 88, 71, 89],
       [89, 13, 59, 66]])

In [35]:
L=[25,45,6,67]  

In [36]:
L_sub=L[:2]

In [37]:
L_sub

[25, 45]

In [38]:
L_sub[1]=778

In [39]:
L_sub

[25, 778]

In [40]:
L                 #changed value does not reflect in original list

[25, 45, 6, 67]

In [41]:
L1=[[1,2,3,4],[5,6,7,8]]

In [42]:
L1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [43]:
L1[0]

[1, 2, 3, 4]

In [44]:
L1_sub=L1[0]

In [45]:
L1_sub

[1, 2, 3, 4]

In [46]:
L1_sub[2]=777

In [47]:
L1_sub

[1, 2, 777, 4]

In [48]:
L1

[[1, 2, 777, 4], [5, 6, 7, 8]]

In [49]:
type(L1)

list

In [50]:
print(y)

[[45 88 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]]


In [51]:
y_sub=y[:2,:2]
print(y_sub)

[[45 88]
 [68 10]]


In [52]:
y_sub[0,0]=888
print(y_sub)

[[888  88]
 [ 68  10]]


In [53]:
print(y)

[[888  88  65  68]
 [ 68  10  84  22]
 [ 37  88  71  89]
 [ 89  13  59  66]]


In [54]:
y_sub_copy=y_sub.copy()

In [55]:
print(y_sub_copy)

[[888  88]
 [ 68  10]]


In [56]:
y_sub_copy[0,0]=444
print(y_sub_copy)

[[444  88]
 [ 68  10]]


In [57]:
print(y_sub)  #copy function creates another object itself hence changes are not reflected.

[[888  88]
 [ 68  10]]


In [58]:
y

array([[888,  88,  65,  68],
       [ 68,  10,  84,  22],
       [ 37,  88,  71,  89],
       [ 89,  13,  59,  66]])

In [62]:
L=[1,2,3,4,5,6,7,8]
print(L)

[1, 2, 3, 4, 5, 6, 7, 8]


In [63]:
L_sub=L[:3]
print(L_sub)

[1, 2, 3]


In [64]:
L_sub[2]=777

In [65]:
print(L_sub)

[1, 2, 777]


In [66]:
print(L)   # change does not reflect in lists.

[1, 2, 3, 4, 5, 6, 7, 8]


# Reshaping arrays.

In [68]:
grid=np.arange(1,10).reshape(3,3) # arange function gives us numbers from start to end-1, reshape changes the dimension of array.
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
x=np.array([1,2,3])
x.reshape(1,3) #1-d to 2-d via reshape

array([[1, 2, 3]])

In [73]:
x[np.newaxis,:] # row vector

array([[1, 2, 3]])

In [75]:
x[:,np.newaxis] # column vector

array([[1],
       [2],
       [3]])

In [76]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [77]:
z=[77,88,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 77 88 99]


In [114]:
#concatenate along the first axis 
grid=np.array([[1,2,3],[4,5,6]])
#grid
np.concatenate([grid,grid])
#grid[1,0]

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [108]:
#concatenate along the second axis
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [109]:
#vertically stack the arrays
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [110]:
#horizontally stack the arrays
y=np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [1]:
pwd

'C:\\Users\\Dattu'